learners/setup.md

add packages from new episodes (#23)

---

config.yaml
episodes/quantify-transmissibility.Rmd

in sync with https://github.com/epiverse-trace/tutorials-early/pull/37

hide Rt episode in sync with copy to tutorials-early

---

index.md
learners/setup.md

move index to setup + update installations

---

learners/setup.md

add installation for superspreading episodes

---

learners/setup.md

add chunk to install packages on superspreading

---

learners/setup.md

add steps to install rtools for epinow2 in windows computers

---

episodes/superspreading-simulate.Rmd

use multiple chain summary to count threshold

---

learners/setup.md

as reported by @jamesmbaazam 🎊

add epichains installation from CRAN

---

.github/workflows/sandpaper-main.yaml

* **Please check if the PR fulfills these requirements**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
* **What is the current behavior?** (You can also link to an open issue here)
* **What is the new behavior (if this is a feature change)?**
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
* **Other information**:

Test ubuntu 24.04

---

locale/es/episodes/create-forecast.Rmd
locale/es/episodes/delays-functions.Rmd

Fixing pegboard validation errors flagged in https://github.com/epiverse-trace/tutorials-middle-es/actions/workflows/dovetail-main.yaml

Fix div names in Spanish version

---

episodes/delays-access.Rmd

simplify accessing paramters + refer to distributions interfase

---

episodes/quantify-transmissibility.Rmd

diagnosed during last delivery

slice cases from top chunk

---

instructors/data-covid-filter.R
instructors/data-severity-static.R

add explicit aim to data creation files

update package interfase of severity data

---

episodes/severity-static.Rmd

replace `epidist` with `epiparameter`

---

episodes/superspreading-simulate.Rmd

replace `epidist` with `epiparam`

---

episodes/quantify-transmissibility.Rmd

- fixing #159 
- for consistency with #158 and https://epiforecasts.io/EpiNow2/reference/epinow.html

fix "confirmed cases" to disease reports (confirm)

---

episodes/superspreading-simulate.Rmd

fit lesson aim with content

---

learners/setup.md

update readme as in https://github.com/epiverse-trace/tutorials-early/pull/177

update setup from early tutorials

---

.github/workflows/README.md
.github/workflows/pr-receive.yaml
.github/workflows/sandpaper-main.yaml

Now that https://github.com/carpentries/actions/pull/101 has been merged.

Revert to using carpentries official action

---

episodes/superspreading-simulate.Rmd

- use discrete distributions
- separate multiple from iterations
- fix and hide solutions

update episode content

---

episodes/delays-functions.Rmd

* **Please check if the PR fulfills these requirements**

Fix delays functions late
